const products = [
    {
      id: 1,
      title: 'Apple watch',
      description: 'Series 5 SE',
      rating: '⭐⭐⭐⭐',
      price: 529.99,
      currency: '$',
      imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGFwcGxlJTIwd2F0Y2h8ZW58MHx8MHx8fDA%3D&w=1000&q=80',
      specs: [
        'Introducing the Apple Watch Series 5 SE, a cutting-edge blend of style, functionality, and innovation, designed to accompany you on every step of your journey. Embrace the future with this versatile smartwatch, packed with features to suit both daily needs and adventurous lifestyles. Whether you are a tech enthusiast seeking the latest gadget or someone looking to enhance your daily life with smart technology, the Apple Watch Series 5 SE offers something for everyone. Its more than just a watch its a lifestyle companion. Invest in yourself and embrace the future of wearable technology. Order the Apple Watch Series 5 SE today and take the first step towards a smarter, healthier, and more connected life.',
      ],
    },
  {
      id: 2,
      title: 'Sony ZX3',
      description: 'Light Grey',
      rating: '⭐⭐⭐',
      price: 39.99,
      currency: '$',
      imageUrl: 'https://m.media-amazon.com/images/I/61DeaUKGHrL._AC_UF350,350_QL80_.jpg',
      specs: [
        'Experience the true essence of music with Sony ZX330BT Headphones, designed for those who live, breathe, and dream sound. With unmatched comfort and innovative technology, these wireless headphones bring you closer to your favorite tracks, offering an immersive auditory experience like no other. Sonys ZX330BT Headphones are more than just an accessory; they are an extension of your personality and a testament to your passion for music. Whether you are at home, on a commute, or taking a break from the world, these headphones provide an escape to a world where only music matters. Indulge in the sound. Experience comfort. Embrace the Sony ZX330BT Headphones today and redefine what music means to you.',
      ],
    },
    {
      id: 3,
      title: 'iPhone 11',
      description: 'Serious Black',
      rating: '⭐⭐⭐⭐⭐',
      price: 619.99,
      currency: '$',
      imageUrl: 'https://www.tradeinn.com/f/13735/137354156/apple-iphone-11-128gb-6.1.jpg',
      specs: [
        'Display: Liquid Retina HD display',
        'Processor: A13 Bionic chip',
        'Camera System: Dual 12MP Ultra Wide and Wide cameras',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 17 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
      ],
    },
    {
      id: 4,
      title: 'iPhone 11',
      description: 'Subway Blue',
      rating: '⭐⭐⭐⭐⭐',
      price: 619.99,
      currency: '$',
      imageUrl: 'https://blgtm.com/wp-content/uploads/2019/12/ExternalLink_iphone11-green-select-2019_GEO_EMEA',
      specs: [
        'Display: Liquid Retina HD display',
        'Processor: A13 Bionic chip',
        'Camera System: Dual 12MP Ultra Wide and Wide cameras',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 17 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
      ],
    },
    {
      id: 5,
      title: 'iPhone 11',
      description: 'Product Red',
      rating: '⭐⭐⭐⭐⭐',
      price: 619.99,
      currency: '$',
      imageUrl: 'https://epicdeals.co.za/wp-content/uploads/2022/10/iPhone-13-Product-Red-Cover-Image.png',
      specs: [
        'Display: Liquid Retina HD display',
        'Processor: A13 Bionic chip',
        'Camera System: Dual 12MP Ultra Wide and Wide cameras',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 17 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
      ],
    },
    {
      id: 6,
      title: 'iPhone 11',
      description: 'Milky White',
      rating: '⭐⭐⭐⭐⭐',
      price: 619.99,
      currency: '$',
      imageUrl: 'https://micellpty.com/wp-content/uploads/2023/04/iphone-12-pro-max-1-1-1.jpg',
      specs: [
        'Display: Liquid Retina HD display',
        'Processor: A13 Bionic chip',
        'Camera System: Dual 12MP Ultra Wide and Wide cameras',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 17 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
      ],
    },
    {
      id: 7,
      title: 'iPhone 13',
      description: 'Product Red',
      rating: '⭐⭐⭐⭐⭐',
      price: 699.00,
      currency: '$',
      imageUrl: 'https://www.hificorp.co.za/media/catalog/product/cache/7ce9addd40d23ee411c2cc726ad5e7ed/i/p/iphone_13_red_pure_back_iphone_13_red_front_128gb_ecommerce_8549.png',
      specs: [
        'Display: Super Retina XDR display',
        'Processor: A15 Bionic chip',
        'Camera System: Dual 12MP Ultra Wide and Wide cameras with Night mode',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 22 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 6 meters up to 30 minutes)',
      ],
    },
    {
      id: 8,
      title: 'iPhone 14',
      description: 'Product Red',
      rating: '⭐⭐⭐⭐⭐',
      price: 619.99,
      currency: '$',
      imageUrl: 'https://images.squarespace-cdn.com/content/v1/59d2bea58a02c78793a95114/1638557435572-UYISRNGX323H0CMYA0XM/iPhone+13.png?format=1000w',
      specs: [
        'Display: Super Retina XDR display',
        'Processor: A16 Bionic chip',
        'Camera System: Triple 12MP Ultra Wide, Wide, and Telephoto cameras',
        'Face ID: Enabled for secure authentication',
        'Battery Life: Up to 24 hours of talk time',
        'Water Resistance: Rated IP68 (maximum depth of 6 meters up to 30 minutes)',
      ],
    },
  ];
  export default products;
